### ISSUE TITLE
rn2903A is not transmittingdta while rn2903 is worinkg perfectly

### ISSUE THREAD

**Issue by cheeta1** [jpmeijers/RN2483-Arduino-Library#48]

**Comment by cheeta1** [comment]
i have rn2903A modules. they are responding perfectly on serial but my gateway does not receive the data packect while rn2903 are working perfeclty and gateway is receiving data from them.

**Comment by jpmeijers** [comment]
This sounds like you have a 915MHz gateway. The RN2483 is a 868MHz radio and will not be received by a 915MHz gateway. The RN2903 is a 915MHz radio and will be received by a 915MHz gateway.

Does this explain your situation?
