### ISSUE TITLE
Encoding error in TheThingsUno-GPSshield-TTN-Mapper-binary.ino example

### ISSUE THREAD

**Issue by testert1ng** [jpmeijers/RN2483-Arduino-Library#53]
The encoding part for **hdop** looks not correct in [TheThingsUno-GPSshield-TTN-Mapper-binary.ino](https://github.com/jpmeijers/RN2483-Arduino-Library/blob/master/examples/TheThingsUno-GPSshield-TTN-Mapper-binary/TheThingsUno-GPSshield-TTN-Mapper-binary.ino#L195) example.

As the [decoder](https://github.com/jpmeijers/RN2483-Arduino-Library/blob/master/examples/TheThingsUno-GPSshield-TTN-Mapper-binary/TheThingsUno-GPSshield-TTN-Mapper-binary.ino#L64) part dividing by 10, the encoder should multiply by 10.

``` C
// should be multiplication (*) here
hdopGps = gps.hdop.value()/10;
```

**Comment by jpmeijers** [comment]
This is actually correct, because the library gives the HDOP in "hundredths". 
And because `100/10 == 1*10`, this is in fact correct.
